site_name: Merlin
repo_url: https://github.com/sammarxz/merlin
repo_name: sammarxz/Merlin
edit_uri: tree/main/docs

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css
